# Generated by Django 3.0.2 on 2020-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=120)),
                ('price_item', models.CharField(max_length=120)),
                ('desciption_item', models.CharField(max_length=120)),
            ],
        ),
    ]
