# Generated by Django 3.0.2 on 2020-04-05 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_item',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
