# Generated by Django 3.0.2 on 2020-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_items', '0003_add_item_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_item',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
