# Generated by Django 3.0.2 on 2020-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_items', '0004_add_item_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_item',
            name='model_pic',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
