# Generated by Django 2.2.7 on 2020-04-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200324_1438'),
        ('goods', '0002_auto_20200405_0621'),
    ]

    operations = [
    ]
